version: "3.9"
services:

    mysql:
        image: mysql:8.0.30-oracle
        container_name: mysql
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - sql-data:/var/lib/mysql
        healthcheck:
            start_period: 10s # (default value 0sec)
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
            timeout: 20s
            retries: 10
            #interval: 30s (default value 30sec)

    patient-app:
        build: patient
        #image: patient_app
        container_name: patient-app
        environment:
            MYSQL_URL: ${MYSQL_URL} #:3306 (Not required when there is only one port in the container)
            MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

        ports:
            - '8081:8081'
        depends_on:
            mysql:
                condition: service_healthy
                #healthcheck:
                #test: [ "CMD", "curl --fail http://localhost:8081/actuator/health || exit 1" ]
                #timeout: 20s
                #retries: 3

    mongodb:
        image: mongo:latest
        container_name: mongodb
        environment:
            MONGODB_DATABASE_NAME: ${MONGODB_DATABASE}
        volumes:
            - nosql-data:/data/db

    note-app:
        build: note
        #image: note_app
        container_name: note-app
        environment:
            MONGODB_URL: ${MONGODB_URL}
            MONGODB_DATABASE: ${MONGODB_DATABASE}
        ports:
            - '8082:8082'
        depends_on:
            - mongodb

    report-app:
        build: report
        #image: report_app
        container_name: report-app
        environment:
            PATIENT_HOST: ${PATIENT_HOST}
            NOTE_HOST: ${NOTE_HOST}
        ports:
            - '8083:8083'
        depends_on:
            - patient-app
            - note-app

    client-app:
        build: client
        #image: client-app
        container_name: client-app
        environment:
            PATIENT_HOST: ${PATIENT_HOST}
            NOTE_HOST: ${NOTE_HOST}
            REPORT_HOST: ${REPORT_HOST}
        ports:
            - '80:8080'
        depends_on:
            - report-app

volumes:
    sql-data:
    nosql-data:
