version: "3.9"
services:

    mysql:
        image: mysql:8.0.30-oracle
        container_name: mysql
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - sql-data:/var/lib/mysql
        healthcheck:
            start_period: 10s #(default value 0sec)
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
            timeout: 20s
            retries: 10
            #interval: 30s (default value 30sec)

    patient-app:
        build: patient
        #image: patient_app
        container_name: patient-app
        environment:
            MYSQL_URL: mysql #:3306 (Not required when there is only one port in the container)
            MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
            MYSQL_USER: root
            MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}

        ports:
            - '8081:8081'
        depends_on:
            mysql:
                condition: service_healthy
    #        healthcheck:
    #            test: ["CMD", "curl --fail http://localhost:8081/actuator/health || exit 1"]
    #            timeout: 20s
    #            retries: 3

    mongodb:
        image: mongo:latest
        container_name: mongodb
        volumes:
            - nosql-data:/data/db

    note-app:
        build: note
        #image: note_app
        container_name: note-app
        environment:
            MONGODB_URL: mongodb
            MONGODB_DATABASE: note
        ports:
            - '8082:8082'
        depends_on:
            - mongodb

    report-app:
        build: report
        #image: report_app
        container_name: report-app
        environment:
            PATIENT_HOST: patient-app:8081
            NOTE_HOST: note-app:8082
        ports:
            - '8083:8083'
        depends_on:
            - patient-app
            - note-app

    client-app:
        build: client
        #image: client-app
        container_name: client-app
        environment:
            PATIENT_HOST: patient-app:8081
            NOTE_HOST: note-app:8082
            REPORT_HOST: report-app:8083
        ports:
            - '80:8080'
        depends_on:
            - report-app

volumes:
    sql-data:
    nosql-data:
